-- =====================================================
-- 001_init.sql
-- Initial schema (INTEGER IDs + id_external)
-- =====================================================

CREATE TABLE IF NOT EXISTS basin (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_external TEXT UNIQUE,
  name TEXT NOT NULL,
  meta JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS river (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_external TEXT UNIQUE,
  name TEXT NOT NULL UNIQUE,
  basin_id INTEGER REFERENCES basin(id) ON DELETE SET NULL,
  meta JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS station (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_external TEXT NOT NULL UNIQUE, -- objID
  code TEXT,                        -- DBC
  name TEXT NOT NULL,
  river_id INTEGER REFERENCES river(id) ON DELETE SET NULL,
  basin_id INTEGER REFERENCES basin(id) ON DELETE SET NULL,
  operator TEXT,
  lat DOUBLE PRECISION,
  lon DOUBLE PRECISION,
  elevation_m DOUBLE PRECISION,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  meta JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS measurement (
  station_id INTEGER NOT NULL REFERENCES station(id) ON DELETE CASCADE,
  ts TIMESTAMPTZ NOT NULL,
  water_level_cm NUMERIC,
  discharge_m3s NUMERIC,
  source TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (station_id, ts)
);

CREATE TABLE IF NOT EXISTS ingest_run (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind TEXT NOT NULL, -- 'discover' | 'ingest'
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at TIMESTAMPTZ,
  status TEXT NOT NULL, -- 'ok' | 'error'
  details JSONB NOT NULL DEFAULT '{}'::JSONB
);

CREATE INDEX IF NOT EXISTS idx_ingest_run_kind_started_at
  ON ingest_run (kind, started_at DESC);


CREATE INDEX IF NOT EXISTS idx_measurement_station_ts
  ON measurement (station_id, ts DESC);

CREATE INDEX IF NOT EXISTS idx_station_river
  ON station (river_id);

CREATE INDEX IF NOT EXISTS idx_station_basin
  ON station (basin_id);

CREATE INDEX IF NOT EXISTS idx_station_id_external
  ON station (id_external);
