-- =====================================================
-- 004_payments.sql
-- Payment tracking + FIO rate limit singleton
-- =====================================================

CREATE TABLE IF NOT EXISTS payment (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  amount INTEGER NOT NULL,
  vs TEXT NOT NULL UNIQUE,
  plan TEXT NOT NULL CHECK (plan IN ('monthly', 'yearly')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'expired')),
  fio_transaction_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  paid_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_payment_user ON payment(user_id);
CREATE INDEX IF NOT EXISTS idx_payment_vs ON payment(vs);
CREATE INDEX IF NOT EXISTS idx_payment_status ON payment(user_id, status);

CREATE TABLE IF NOT EXISTS fio_rate_limit (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  last_fetched_at TIMESTAMPTZ NOT NULL DEFAULT '1970-01-01T00:00:00Z'
);

INSERT INTO fio_rate_limit (id) VALUES (1) ON CONFLICT DO NOTHING;
